services:
  db:
    build: .
    container_name: rankingPro-admin-db
    restart: always
    tty: true
    #Left is the machine port and right is the container port
    ports:
      - '${DB_PORT}:5432'
    # Get the data stored by postgres into container in the path in colon right-side and put in left-side path in the application
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    # When the user is not defined, it's created with default user: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

